### Read all films with File variable
@baseUrl = http://localhost:3000
GET {{baseUrl}}/films

### Read all films with a bigger or equals duration than 120
GET {{baseUrl}}/films?minimum-duration=120

### Create a pizza
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title":"Avatar",
    "duration": 140,
    "budget" : 1300000,
    "link" : "https://"
}