### Read all textes
@baseUrl = http://localhost:3000
GET {{baseUrl}}/texte

### Read all textes with a value like easy 
GET {{baseUrl}}/texte?value=easy

### Read a texte by the ID 2
GET {{baseUrl}}/texte/7456fd08-6405-4831-96b2-c80722ba9924

### Create a texte 
POST {{baseUrl}}/texte
Content-Type: application/json

{
    "content" : "Ecrire sur le clavier des mots de base",
    "level" : "easy"
}

### delete a film from FILMS by the ID
DELETE {{baseUrl}}/texte/0fb14334-e23d-4300-a3f1-03e6f8634ad1

### update a film or create by the ID
PUT {{baseUrl}}/texte/0fb14334-e23d-4300-a3f1-03e6f8634ad1
Content-Type: application/json

{
    "content" : "Ecrire un texte dans un format précis",
    "level" : "hard"
}
